### ISSUE TITLE
Print glitches on (possibly) high dpi screens?

### ISSUE THREAD

**Issue by fu5ha** [larskarbo/napchart#16]
Just tested on my macbook pro and got a weird result. Will try to look into it at some point..

![glitch](http://i.imgur.com/U4LzOW5.png)

**Comment by larskarbo** [comment]
I can't verify but I also think it is because of high dpi. All high dpi handling is now done around here: https://github.com/larskarbo/napchart/blob/master/public/js/draw.js#L1008

Don't be afraid of doing big structural changes to the codebase if you think you have a good way to do it.

**Comment by larskarbo** [comment]
Outdated, no print in current version
