### ISSUE TITLE
Cant export to pdf on mobile

### ISSUE THREAD

**Issue by larskarbo** [larskarbo/napchart#17]
When trying to save as pdf on Iphone 6s, it does not work.

Chrome: Opens a new about:blank with nothing
Safari: Nothing happens

**Comment by larskarbo** [comment]
@termhn if you want to, you could have a look at this one too. I am busy for some time

**Comment by fu5ha** [comment]
@larskarbo sure. Looks like it's due to running out of memory in the canvas.toDataURL... I'll look at scaling the canvas momentarily when a print call happens, should solve this and the high dpi issues.

**Comment by larskarbo** [comment]
The new version doesn't support pdf export.

Leaving this issue open so that we can add the future again in the future
