### ISSUE TITLE
Missing Dymaxion sleep schedule

### ISSUE THREAD

**Issue by mkarnicki** [larskarbo/napchart#19]
Dymaxion schedule is based on 4 30-minute naps spread throughout the day. Hence, total sleep time is 2 hours and up-time is 22 hours.

**Comment by larskarbo** [comment]
Yes, this is a good idea

If you want to give it a shot yourself you can have a look at 'main.ejs' and 'sampleSchedules.js' and submit a pull request

**Comment by mkarnicki** [comment]
Any chance you'll deploy this to the site? :)

**Comment by larskarbo** [comment]
@mkarnicki I am not able to do it right now, but ai can have a look at it in a week or so.

But you can also do it yourself if you want to. Make a pull request and I will merge and deploy it. Ask me if you need help!

**Comment by mkarnicki** [comment]
Hi @larskarbo, thank you for replying :). I'm not sure what you mean by pull request, as I have already provided it, and you have merged it on Jan 17. Since it's been a month I thought I'd just ask if you plan to deploy my fix :). No worries, I'm not in rush. I just thought it would be useful.

**Comment by larskarbo** [comment]
@mkarnicki Oh sorry, my bad! I have deployed it now.
