### ISSUE TITLE
Colour-coding of different busy elements

### ISSUE THREAD

**Issue by Theleruby** [larskarbo/napchart#23]
When I'm building a napchart right now you have core, nap and busy. Sleeps are in red and busy periods in grey. I would really like to be a bit more detailed than this, e.g. instead of "busy" I would like to have "working" and "travelling" so I can label those separately. I would also like these to be in separate colours, maybe with the ability to choose the colour for each thing. For example, I might choose to have 'travelling' sections in green.

**Comment by larskarbo** [comment]
Definitely a good point. I am in the process of overhauling the whole app and will make it more customizable

**Comment by larskarbo** [comment]
It's done, you can now use 4 different colors
