### ISSUE TITLE
Please add more standard cycles

### ISSUE THREAD

**Issue by Theleruby** [larskarbo/napchart#24]
/r/polyphasic lists 14 standard polyphasic sleeping cycles as thus:
https://i.imgur.com/wtl3SSP.jpg
https://i.imgur.com/Z2h69DK.jpg
https://i.imgur.com/jeQzTbW.jpg
https://i.imgur.com/xb5UhMs.jpg

napchart however only includes 7 of these. It would be nice if it had all of them available by default.

**Comment by larskarbo** [comment]
Im not sure how to implement all possible schedules into the app without it being cluttered

**Comment by larskarbo** [comment]
The new version includes many schedules
