### ISSUE TITLE
setting custom url doesn't work

### ISSUE THREAD

**Issue by DavidGretzschel** [larskarbo/napchart#25]
Example:
I wanted to save this schedule under the name:
https://napchart.com/lionman,
but sadly it gave me the less descriptive url:
https://napchart.com/dui9k

Having that field be editable sets up an expectation, 
that's subverted here.
Not sure, why editing the url is possible in the first place.
Maybe, make that a bit more obvious?
In any case, being able to set custom-urls would be awesome.

**Comment by larskarbo** [comment]
The reason why the input element is not readonly is that it makes it harder to select the text. But maybe there is another way to make it obvious that you can't actually edit the url?

I am not sure if it is a good idea to make users able to create custom urls. Maybe in the future we can do that if we follow this system: napchart.com/user/chart where user is your username.
