### ISSUE TITLE
add simple textfield to add description

### ISSUE THREAD

**Issue by DavidGretzschel** [larskarbo/napchart#26]
I'd like to have a text field to add to my napchart to add some descriptions.
This would be helpful for weirder things like SPAMMAYL and allow to
redefine the 'work'-zones for something else (like no-coffee zones for example).

EDIT:
Also a field to enter a name. That could make conversations more precise,
when people are copying each others schedule.

**Comment by larskarbo** [comment]
I agree that this would be a useful addition to the app.

I am working at porting napchart over to using react, and the next version will include this.

Let me know if you have more thoughts!

**Comment by larskarbo** [comment]
> EDIT:
> Also a field to enter a name. That could make conversations more precise,
when people are copying each others schedule.

I am thinking of adding a title field and a description field where users can write in detail about the schedule

**Comment by larskarbo** [comment]
Hi, theese features exist in the new version of Napchart released now
