### ISSUE TITLE
Adding More Colors/Sections

### ISSUE THREAD

**Issue by mitchell11678** [larskarbo/napchart#30]
It would be very handy to be able to add more colors to the napchart, such as instead of their being the set grey, blue, green. There could just be a plus button and the ability to set a color based on the color wheel/pallet. This would allow for the setting of more activities, for instance on my napchart https://napchart.com/7glsb I would have liked to have four colors, with the fourth being a set time for fasting.

**Comment by larskarbo** [comment]
Yes, this would be possible. Only thing I worry about is the UI being too cluttered when adding many colors, but I'm sure there is a way

**Comment by larskarbo** [comment]
The website part of napchart has now moved to [napchart-website](https://github.com/larskarbo/napchart-website), whereas this repository is the canvas library only.

Good news: v3 of `napchart-website` includes many more colors. It will soon be pushed to production, but in the meanwhile you can clone your own version to test it
