### ISSUE TITLE
Add Contribution Intro (& Guidelines) to README.md

### ISSUE THREAD

**Issue by njoye** [larskarbo/napchart#35]
I'd like to help but it's quite a drawback to not have a little introduction on what needs to be setup / is needed. This is not as bad for me as for others since I'll simply try to get into the system, but for people not programming that long that want to contribute this could be a little problem :) 

And also Contribution Guidelines would make it easier for others to contribute some code.

This is not critical or something, but it would be very useful for developers.

**Comment by larskarbo** [comment]
Yep, I agree. I have some plans to make a few breaking changes and clean up the code base a little, and hope to add a Contribution Guidelines in the process. Will probably take a few weeks

**Comment by larskarbo** [comment]
With the release of `v3` a `CONTRIBUTING.md` file has been created here, and in `napchart-website`.

Not finished yet, but at least there is something
