### ISSUE TITLE
Delete chart elements

### ISSUE THREAD

**Issue by TheJayEye** [larskarbo/napchart#40]
Currently no way to modify(delete) a given chart unless starting over.

**Comment by larskarbo** [comment]
The new way in v3 to delete an element is to set the duration to zero and release

**Comment by TheJayEye** [comment]
is the website up to date because i cant seem to delete?

**Comment by larskarbo** [comment]
No, the website is not up to date yet. There are a few things to sort out before I push the `v3` release
