### ISSUE TITLE
feature: Whole lane shift

### ISSUE THREAD

**Issue by zeorin** [larskarbo/napchart#42]
Hi! Love your work.

It'd be really useful to shift/move an entire lane back and forth, not just individual elements in that lane.

Especially when designing a polyphasic schedule, one might first pay more attention to the rhythm of sleep blocks than their start times.
Being able to shift the entire lane to line up with other times whilst maintaining the gaps between sleep blocks would be very handy.

**Comment by larskarbo** [comment]
This is a somewhat forgotten feature. It was in the previous release and should have already been in the current. I have to decide if it should be a job for this repo or `napchart-website`. Will have a look at it

**Comment by larskarbo** [comment]
@zeorin 

Fixed in the release today

https://blog.napchart.com/new-ui-and-features/
