### ISSUE TITLE
Option to display gap between phases (see poly examples)

### ISSUE THREAD

**Issue by ninichat** [larskarbo/napchart#44]
This would be nice to have an option to see the lengths of time there is between the different phases.
This probably shouldn't be done by default as it might clutter the whole chart.

Alos, would it be possible to add something in the url to enable such option, when seeing the chart / generating the chart's thumbnail? This might be a feature for napchart website though.

Thanks for your awesome work!

**Comment by larskarbo** [comment]
It already shows time between elements on the same lane if one of the elements is selected. When you deselect, the distances disappear

Adding it as a parameter to draw when accessing image from server is not a bad idea. However, I am not sure I would add it by default.

When bots visit napchart.com/xxxxx they read the `og-image` field that has the value `https://napchart.com/api/getImage?chartid=xxxxx&width=600&height=600&shape=circle`. It would be no problem to for example add an option `distances=true`, but then it would be served like that to all bots, even though it is most useful for the *discord* bot (wild guessing that thats the place you think of)

**Comment by ninichat** [comment]
In that case, were the bot to actually query
`https://napchart.com/api/getImage?chartid=xxxxx&width=600&height=600&shape=circle&distances=choice` itself, he could get the version it wants, right?

Taking it one step further, could either of these query become possible:
- `https://napchart.com/api/getImage?chartid=xxxxx&width=default&height=default&shape=default&distances=choice`
- `https://napchart.com/api/getImage?chartid=xxxxx`

Or maybe could og-image be modified when reading napchart.com/id, using url parameters?

If in the future more options are added, it could be useful for the bots to be able to customize them, while keeping the default values for the ones they don't need to customize.

**Comment by larskarbo** [comment]
The problem is that the bots (crawlers) always use the exact `og-image` value, and that value will be the same whether it's facebook or discord or any other bot

Possibilities will be
1.  use `distances=true` for ALL crawlers
2. discord bot implement some logic to always fetch the `distances=true` version (not sure if possible)
3. make a custom rule on napchart servers to always serve `distances=true` when it detects discord bot (possible, but hacky)

Do you see any other possibilities?

**Comment by ninichat** [comment]
Would it be possible to add parameters in the napchart.com/id url, modifying the og-image for the specified url?
Example: napchart.com/xxxxx&arg1=x&arg2=x

Otherwise the bots themselves could be modified to directly query the api url, but that's a bit hacky as well.

**Comment by larskarbo** [comment]
Feels a bit hacky, I think we'll have to look at this issue when fixing #43
