### ISSUE TITLE
Image & Save URL missing "/"

### ISSUE THREAD

**Issue by pixelwiese** [larskarbo/napchart#47]
When I save a created Chart I get an URL like: `https://napchart.comhnb9c` 
1. The "/" is missing
2. It seems that the URLs do not work with the "https://" (on napchart.com) I think this is a problem with a missing certificate.

The same Problem occurs for the Image-URLs.
`https://napchart.comapi/getImage?width=600&height=600&chartid=plypn`
Without the "https://" and with the "/" everything works fine.

**Comment by dreaming-augustin** [comment]
I used to have a similar problem, but I cannot reproduce anymore. Apparently the bug has been quietly fixed.

I think I remember the link in `Share > IMAGE Image link (600x600)` used to be broken, but it appears to be ok, now. 

@pixelwiese : if you can still reproduce the bug, can you provide information and links that would show how to reproduce it?
If not, I think this issue can be closed.

**Comment by pixelwiese** [comment]
Looks fine for me too. Can be closed.
