### ISSUE TITLE
App showing am/pm and not 24h anymore

### ISSUE THREAD

**Issue by twirley** [larskarbo/napchart#53]
Hi,
is there a way to have the 24h layout back, at least have the option to change it?

**Comment by larskarbo** [comment]
hi @twirley ! thanks for the issue.

Does it work if you select 24 in the config in about?

![shot-9nU0Owcn](https://user-images.githubusercontent.com/10865165/223402363-64310297-6ff4-4d9e-8875-9111221e51b0.png)

**Comment by twirley** [comment]
yes...
it is there. I don't understand how I didn't see it before, although I was in that field a couple of times checking...

Thank you for the quick reply
