### ISSUE TITLE
Sampleschedules is not enabled on small screens

### ISSUE THREAD

**Issue by larskarbo** [larskarbo/napchart#9]
Somehow make the sampleschedules available on small screens.

It should be a slider menu from the left or something, otherwise it would take too much space

**Comment by algor1th** [comment]
Do you use any css framework? I may be able to do a collapsable, if it needs to be a slider menu i will have to do some research
Edit: found out you use materialize

**Comment by larskarbo** [comment]
It doesn't need to be a slider menu. In fact, it may be best if it is a collapsable.

Give it a shot!

**Comment by algor1th** [comment]
Should this be marked as done?

**Comment by larskarbo** [comment]
Yes, I forgot that, thank you
